-- Make admin-managed upgrade banners safe for older installations.
-- Run after 004_promo_banners.sql and 005_restore_legacy_promo_banners.sql.
-- This migration is idempotent and does not delete existing banner content.

create table if not exists public.promo_banners (
  id bigint generated by default as identity primary key,
  title text not null default 'Upgrade to Pro',
  body text not null default 'Unlock full monitoring, live screen, and more',
  button_text text not null default 'Upgrade',
  action_url text,
  target_plan text not null default 'ALL',
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.promo_banners add column if not exists title text;
alter table public.promo_banners add column if not exists body text;
alter table public.promo_banners add column if not exists button_text text default 'Upgrade';
alter table public.promo_banners add column if not exists action_url text;
alter table public.promo_banners add column if not exists target_plan text default 'ALL';
alter table public.promo_banners add column if not exists display_order integer default 0;
alter table public.promo_banners add column if not exists is_active boolean default true;
alter table public.promo_banners add column if not exists created_by text;
alter table public.promo_banners add column if not exists updated_by text;
alter table public.promo_banners add column if not exists created_at timestamptz default now();
alter table public.promo_banners add column if not exists updated_at timestamptz default now();
alter table public.promo_banners add column if not exists deleted_at timestamptz;

update public.promo_banners
set title = coalesce(nullif(trim(title), ''), 'Upgrade to Pro'),
    body = coalesce(nullif(trim(body), ''), 'Unlock full monitoring, live screen, and more'),
    button_text = coalesce(nullif(trim(button_text), ''), 'Upgrade'),
    target_plan = case when upper(coalesce(target_plan, 'ALL')) in ('ALL','TRIAL','FREE','PRO','PREMIUM') then upper(coalesce(target_plan, 'ALL')) else 'ALL' end,
    display_order = greatest(coalesce(display_order, 0), 0),
    is_active = coalesce(is_active, true),
    updated_at = coalesce(updated_at, now())
where true;

create index if not exists promo_banners_active_order_idx
  on public.promo_banners(is_active, display_order, created_at);

alter table public.promo_banners enable row level security;

-- Keep at least one editable default banner available to the Parent app.
insert into public.promo_banners (title, body, button_text, target_plan, display_order)
select 'Upgrade to Pro', 'Unlock full monitoring, live screen, and more', 'Upgrade', 'ALL', 0
where not exists (
  select 1 from public.promo_banners where is_active = true and deleted_at is null
);
