-- Admin-managed upgrade banners shown in the Parent app.
-- Run once in Supabase SQL Editor. Do not drop existing tables.
create table if not exists public.promo_banners (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  button_text text not null default 'Upgrade',
  action_url text,
  target_plan text not null default 'ALL' check (target_plan in ('ALL','TRIAL','FREE','PRO','PREMIUM')),
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists promo_banners_active_order_idx
  on public.promo_banners(is_active, display_order, created_at);
alter table public.promo_banners enable row level security;

-- Seed the existing three-card experience once so the Admin Panel can edit it.
insert into public.promo_banners (title, body, button_text, target_plan, display_order)
select 'Upgrade to Pro', 'Unlock full monitoring, live screen, and more', 'Upgrade', 'ALL', 0
where not exists (select 1 from public.promo_banners where deleted_at is null);
insert into public.promo_banners (title, body, button_text, target_plan, display_order)
select 'Upgrade to Pro', 'Unlock full monitoring, live screen, and more', 'Upgrade', 'ALL', 1
where (select count(*) from public.promo_banners where deleted_at is null) = 1;
insert into public.promo_banners (title, body, button_text, target_plan, display_order)
select 'Upgrade to Pro', 'Unlock full monitoring, live screen, and more', 'Upgrade', 'ALL', 2
where (select count(*) from public.promo_banners where deleted_at is null) = 2;
