-- DoraGuard subscription, redeem-code and plan-limit storage.
-- Run after the existing users/subscriptions/admin tables.

create table if not exists public.plan_config (
  plan text primary key check (plan in ('TRIAL','FREE','PRO','PREMIUM')),
  duration_days integer not null default 0 check (duration_days >= 0),
  max_child_devices integer not null default 0 check (max_child_devices >= 0),
  features jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text
);

insert into public.plan_config(plan, duration_days, max_child_devices, features)
values
  ('TRIAL', 3, 1, '{"SCREEN_SHARING":true,"SCREEN_MIRRORING":true,"REMOTE_CAMERA":true,"ONE_WAY_AUDIO":true,"APP_LOCKING":true,"CALL_LOGS":true,"MESSAGE_LOGS":true,"APP_USAGE":true,"LIVE_LOCATION":true,"MAP_LOCATION":true,"PARENTAL_CONTROL":true}'),
  ('FREE', 0, 0, '{"SCREEN_SHARING":false,"SCREEN_MIRRORING":false,"REMOTE_CAMERA":false,"ONE_WAY_AUDIO":false,"APP_LOCKING":false,"CALL_LOGS":false,"MESSAGE_LOGS":false,"APP_USAGE":false,"LIVE_LOCATION":false,"MAP_LOCATION":false,"PARENTAL_CONTROL":false}'),
  ('PRO', 30, 3, '{"SCREEN_SHARING":true,"SCREEN_MIRRORING":true,"REMOTE_CAMERA":true,"ONE_WAY_AUDIO":true,"APP_LOCKING":true,"CALL_LOGS":true,"MESSAGE_LOGS":true,"APP_USAGE":true,"LIVE_LOCATION":true,"MAP_LOCATION":true,"PARENTAL_CONTROL":true}'),
  ('PREMIUM', 365, 10, '{"SCREEN_SHARING":true,"SCREEN_MIRRORING":true,"REMOTE_CAMERA":true,"ONE_WAY_AUDIO":true,"APP_LOCKING":true,"CALL_LOGS":true,"MESSAGE_LOGS":true,"APP_USAGE":true,"LIVE_LOCATION":true,"MAP_LOCATION":true,"PARENTAL_CONTROL":true}')
on conflict (plan) do nothing;

create table if not exists public.redeem_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  plan text not null check (plan in ('TRIAL','FREE','PRO','PREMIUM')),
  duration_days integer not null default 0 check (duration_days >= 0),
  max_uses integer not null default 1 check (max_uses > 0),
  used_count integer not null default 0 check (used_count >= 0),
  expires_at timestamptz,
  active boolean not null default true,
  note text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.redeem_code_redemptions (
  id bigint generated by default as identity primary key,
  code_id bigint not null references public.redeem_codes(id) on delete cascade,
  firebase_uid text not null,
  plan text not null,
  ends_at timestamptz,
  redeemed_at timestamptz not null default now(),
  unique(code_id, firebase_uid)
);

create index if not exists redeem_codes_active_idx
  on public.redeem_codes(active, expires_at);
create index if not exists redeem_redemptions_user_idx
  on public.redeem_code_redemptions(firebase_uid, redeemed_at desc);

-- The child Firebase UID can change after reinstall.  Keep the verified
-- parent owner separately so plan device limits remain correct.
alter table public.device_registry
  add column if not exists owner_firebase_uid text;
create index if not exists device_registry_owner_role_idx
  on public.device_registry(owner_firebase_uid, role);

alter table public.plan_config enable row level security;
alter table public.redeem_codes enable row level security;
alter table public.redeem_code_redemptions enable row level security;